---
- name: add Sensu repository's key
  apt_key: url=https://sensu.global.ssl.fastly.net/apt/pubkey.gpg
           state=present
           validate_certs=no
  environment: "{{proxy_env}}"

# - name: add Sensu repository
#   copy:
#     src=sensu-server.list
#     dest=/etc/apt/sources.list.d/
#     backup=yes
#   register: aptrepo


- name: Install apt-transport-https package for install package with HTTPS via APT
  apt: name=apt-transport-https
       state={{ pkg_state }}
       force=yes
  environment: '{{proxy_env}}'
  tags:
    - pkg

- name: add Sensu repository
  apt_repository: repo='deb https://sensu.global.ssl.fastly.net/apt {{ ansible_distribution_release }} main'
                  state=present
  environment: '{{proxy_env}}'
  register: aptrepo

- name: refresh apt cache
  apt: update_cache=yes
  when: aptrepo.changed
  environment: "{{proxy_env}}"

- name: install sensu
  apt: name=sensu=1.2.1-2 state=present force=yes
  environment: "{{proxy_env}}"

- name: enable sensu-client to survive reboot
  service: name=sensu-client enabled=yes

- name: create the SSL directory
  file:
    path=/etc/sensu/ssl
    owner=sensu
    group=sensu
    mode=0750
    state=directory

- name: copy the SSL certificates
  copy:
    src=ssl/{{ item }}.pem
    dest=/etc/sensu/ssl/{{ item }}.pem
  with_items:
    - cert
    - key

- name: update log level for sensu-client
  lineinfile:
    dest: /etc/default/sensu
    line: 'LOG_LEVEL=warn'
  notify: restart sensu client daemons

- name: copy rabbitmq conf file
  template:
    src=rabbitmq.json.j2
    dest=/etc/sensu/conf.d/rabbitmq.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  notify: restart sensu client daemons

- name: generate /etc/sensu/conf.d/client.json
  template:
    src=sensu.client.config.json.j2
    dest=/etc/sensu/conf.d/client.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  notify: restart sensu client daemons

- name: copy all the plugins
  copy:
    src=sensu/plugins/
    dest=/etc/sensu/plugins/
    owner=sensu
    group=sensu
    mode=0750
  notify: restart sensu client daemons

- name: Install sudo package for sudoers
  apt: name=sudo state=present
  when: ansible_os_family == 'Debian'
  environment: "{{proxy_env}}"

- name: add sensu user to sudoers for sensu checks
  copy: src=10_sensu dest=/etc/sudoers.d/10_sensu owner=root group=root mode=0440

- name: install sensu docker plugins
  shell: "sensu-install -p sensu-plugins-docker"

- name: Add the user 'sensu' to group docker
  user:
    name: sensu
    groups: docker
    append: yes

- name: start sensu-client service
  service: name=sensu-client state=restarted enabled=yes
