global:
  # How frequently to scrape targets by default.
  scrape_interval: 1m
  # How long until a scrape request times out.
  scrape_timeout: 30s
  # How frequently to evaluate rules.
  evaluation_interval: 1m



# A list of scrape configurations.
scrape_configs:

# Scrap infos about prometheus
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

# Scrap netdata infos
- job_name: 'netdata-scrape'
  metrics_path: '/api/v1/allmetrics'
  params:
    # format: prometheus | prometheus_all_hosts
    # You can use `prometheus_all_hosts` if you want Prometheus to set the `instance` to your hostname instead of IP 
    format: [prometheus]

    # sources: as-collected | raw | average | sum | volume
    # default is: average
    #source: [as-collected]

    # server name for this prometheus - the default is the client IP
    # for Netdata to uniquely identify it
    #server: ['prometheus1']
  honor_labels: true
  # static_configs:
  #  - targets: ['192.168.0.17:19999']
  relabel_configs:
    - source_labels: [__address__]
      regex: "([^:]+):\\d+"
      target_label: instance
  file_sd_configs:
      - files:
          - '/etc/prometheus/netdata/*.yml'

