node {

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build image') {
        /* This builds the images */

        def customImage = docker.build("flask:${env.BUILD_ID}")
    }

}
