version: '3.7'
services:

    prometheus:
        image: quay.io/prometheus/prometheus:v2.19.1
        volumes:
            - prometheus_etc:/etc/prometheus
            - prometheus_data:/prometheus
            # - ./prometheus/etc/blackbox:/etc/prometheus/blackbox
            # - ./prometheus/etc/netdata:/etc/prometheus/netdata
            # - ./alertmanager/alert.rules/alerts.rules.yml:/alertmanager/alert.rules/alerts.rules.yml
        ports:
            - "9090:9090"
        command:
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention.time=30d'
            - '--config.file=/etc/prometheus/prometheus.yml'

    grafana:
        image: grafana/grafana:latest
        ports:
            - "5555:3000"
        user: "0"
        environment:
            - "GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/my_secret"
            - "GF_LOG_FILTERS=rendering:debug"
        volumes:
            #- ./grafana/data:/var/lib/grafana
            #- ./grafana/etc:/etc/grafana/provisioning/
            - grafana_data:/var/lib/grafana
            - grafana_etc:/etc/grafana/provisioning
        secrets:
            - my_secret
        links:
            - prometheus
        depends_on:
            - prometheus


volumes:
    prometheus_etc:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/prometheus/etc/
    prometheus_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/prometheus/data/
    grafana_etc:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/grafana/etc/
    grafana_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/grafana/data/

secrets:
  my_secret:
    file: ./my_secret.txt
